var searchData=
[
  ['va_5flist_0',['va_list',['https://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray_1',['valarray',['https://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['valid_2',['valid',['https://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['https://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['https://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()']]],
  ['value_3',['value',['https://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['https://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['https://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['https://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()']]],
  ['value_5fcomp_4',['value_comp',['https://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['https://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()'],['https://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['https://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()']]],
  ['value_5fcompare_5',['value_compare',['https://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap&lt; K, T &gt;::value_compare'],['https://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map&lt; K, T &gt;::value_compare']]],
  ['value_5for_6',['value_or',['https://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['value_5ftype_7',['value_type',['../classca_1_1opt_1_1TransportationSimplex.html#a407ed8ea6f6821dad1ed90d5eb0fe37e',1,'ca::opt::TransportationSimplex']]],
  ['vars_8',['vars',['../structca_1_1opt_1_1Simplex_1_1Context.html#a310e1d98ce917438ae2f5f1a440e3464',1,'ca::opt::Simplex::Context']]],
  ['vec_9',['vec',['../classca_1_1Vec.html#a1ce2ff827d0f9beac566468fafa28b9a',1,'ca::Vec::Vec(VecView&lt; value_type &gt; &amp;&amp;other)'],['../classca_1_1Vec.html#a70c6e925a5dfb7a2d40e78607fd7cd8c',1,'ca::Vec::Vec(const Vec&lt; value_type &gt; &amp;other)'],['../classca_1_1Vec.html#a065df9910f3f322a5b0aeba2e9cf8482',1,'ca::Vec::Vec(const size_type &amp;len)'],['../classca_1_1Vec.html#ae4cb49f1a6685c2f0f19705d874574d3',1,'ca::Vec::Vec(std::initializer_list&lt; value_type &gt; data={})'],['../classca_1_1Vec.html',1,'ca::Vec&lt; T &gt;']]],
  ['vec_3c_20double_20_3e_10',['Vec&lt; double &gt;',['../classca_1_1Vec.html',1,'ca']]],
  ['vec_3c_20typename_20ca_3a_3avec_3c_20t_20_3e_3a_3asize_5ftype_20_3e_11',['Vec&lt; typename ca::Vec&lt; T &gt;::size_type &gt;',['../classca_1_1Vec.html',1,'ca']]],
  ['vec_3c_20value_5ftype_20_3e_12',['Vec&lt; value_type &gt;',['../classca_1_1Vec.html',1,'ca']]],
  ['vecmodel_13',['VecModel',['../classca_1_1qt_1_1VecModel.html',1,'ca::qt']]],
  ['vector_14',['vector',['https://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()'],['https://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector&lt; T &gt;'],['../classca_1_1qt_1_1VecWidget.html#aa37674b263c30bb5cb9f842848aad65a',1,'ca::qt::VecWidget::vector()']]],
  ['vector_3c_20cell_20_3e_15',['vector&lt; Cell &gt;',['https://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20double_20_3e_16',['vector&lt; double &gt;',['https://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vecview_17',['vecview',['../classca_1_1VecView.html',1,'ca::VecView&lt; T &gt;'],['../classca_1_1VecView.html#a503be5ba85a61783e025cadfeb27b780',1,'ca::VecView::VecView()']]],
  ['vecview_3c_20double_20_3e_18',['VecView&lt; double &gt;',['../classca_1_1VecView.html',1,'ca']]],
  ['vecview_3c_20typename_20ca_3a_3avec_3c_20t_20_3e_3a_3asize_5ftype_20_3e_19',['VecView&lt; typename ca::Vec&lt; T &gt;::size_type &gt;',['../classca_1_1VecView.html',1,'ca']]],
  ['vecview_3c_20value_5ftype_20_3e_20',['VecView&lt; value_type &gt;',['../classca_1_1VecView.html',1,'ca']]],
  ['vecwidget_21',['VecWidget',['../classca_1_1qt_1_1VecWidget.html',1,'ca::qt']]],
  ['vfprintf_22',['vfprintf',['https://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_23',['vfscanf',['https://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_24',['vfwprintf',['https://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_25',['vfwscanf',['https://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vprintf_26',['vprintf',['https://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_27',['vscanf',['https://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_28',['vsnprintf',['https://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_29',['vsprintf',['https://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_30',['vsscanf',['https://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_31',['vswprintf',['https://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_32',['vswscanf',['https://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_33',['vwprintf',['https://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_34',['vwscanf',['https://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
