var searchData=
[
  ['va_5flist_0',['va_list',['https://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray_1',['valarray',['https://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['valid_2',['valid',['https://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['https://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['https://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()']]],
  ['value_3',['value',['https://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['https://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['https://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['https://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()']]],
  ['value_5fcomp_4',['value_comp',['https://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['https://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['https://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['https://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp(T... args)']]],
  ['value_5fcompare_5',['value_compare',['https://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap&lt; K, T &gt;::value_compare'],['https://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map&lt; K, T &gt;::value_compare']]],
  ['value_5for_6',['value_or',['https://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['value_5ftype_7',['value_type',['../classca_1_1opt_1_1TransportationSimplex.html#acf5d7ad3ae22ceff889f87e2e176322c',1,'ca::opt::TransportationSimplex']]],
  ['vars_8',['vars',['../structca_1_1opt_1_1Simplex_1_1Context.html#abd8c38a009e6790941bc942577e98212',1,'ca::opt::Simplex::Context']]],
  ['vec_9',['vec',['../classca_1_1vec.html#a6ccfd4e6536859602de8d02ec648be19',1,'ca::vec::vec(std::initializer_list&lt; value_type &gt; data={})'],['../classca_1_1vec.html#a18fe43dcbc77cebcc6a4e8d3154a9b7c',1,'ca::vec::vec(const size_type &amp;len)'],['../classca_1_1vec.html#aeeffa4cbbe8cbc683eb1c86368976520',1,'ca::vec::vec(const vec&lt; value_type &gt; &amp;other)'],['../classca_1_1vec.html#a66f3b0e63bb717b7a5aeafc34588eb54',1,'ca::vec::vec(vec_view&lt; value_type &gt; &amp;&amp;other)'],['../classca_1_1vec.html',1,'ca::vec&lt; T &gt;'],['../classca_1_1ss_1_1vec.html',1,'ca::ss::vec&lt; T &gt;']]],
  ['vec_3c_20distance_5ftype_20_3e_10',['vec&lt; distance_type &gt;',['../classca_1_1vec.html',1,'ca']]],
  ['vec_3c_20double_20_3e_11',['vec&lt; double &gt;',['../classca_1_1vec.html',1,'ca']]],
  ['vec_3c_20typename_20ca_3a_3anum_3a_3abvp_5ftraits_3c_20t_20_3e_3a_3avalue_5ftype_20_3e_12',['vec&lt; typename ca::num::bvp_traits&lt; T &gt;::value_type &gt;',['../classca_1_1vec.html',1,'ca']]],
  ['vec_3c_20typename_20ca_3a_3avec_3c_20t_20_3e_3a_3asize_5ftype_20_3e_13',['vec&lt; typename ca::vec&lt; T &gt;::size_type &gt;',['../classca_1_1vec.html',1,'ca']]],
  ['vec_3c_20value_5ftype_20_3e_14',['vec&lt; value_type &gt;',['../classca_1_1vec.html',1,'ca']]],
  ['vec_5fview_15',['vec_view',['../classca_1_1vec__view.html',1,'ca::vec_view&lt; T &gt;'],['../classca_1_1ss_1_1vec__view.html',1,'ca::ss::vec_view&lt; T &gt;'],['../classca_1_1vec__view.html#a7d8f8356b7d5fd414593c8098c17d981',1,'ca::vec_view::vec_view()']]],
  ['vec_5fview_3c_20distance_5ftype_20_3e_16',['vec_view&lt; distance_type &gt;',['../classca_1_1vec__view.html',1,'ca']]],
  ['vec_5fview_3c_20double_20_3e_17',['vec_view&lt; double &gt;',['../classca_1_1vec__view.html',1,'ca']]],
  ['vec_5fview_3c_20typename_20ca_3a_3anum_3a_3abvp_5ftraits_3c_20t_20_3e_3a_3avalue_5ftype_20_3e_18',['vec_view&lt; typename ca::num::bvp_traits&lt; T &gt;::value_type &gt;',['../classca_1_1vec__view.html',1,'ca']]],
  ['vec_5fview_3c_20typename_20ca_3a_3avec_3c_20t_20_3e_3a_3asize_5ftype_20_3e_19',['vec_view&lt; typename ca::vec&lt; T &gt;::size_type &gt;',['../classca_1_1vec__view.html',1,'ca']]],
  ['vec_5fview_3c_20value_5ftype_20_3e_20',['vec_view&lt; value_type &gt;',['../classca_1_1vec__view.html',1,'ca']]],
  ['vecmodel_21',['VecModel',['../classca_1_1qt_1_1VecModel.html',1,'ca::qt']]],
  ['vector_22',['vector',['https://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector&lt; T &gt;'],['https://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()'],['../classca_1_1qt_1_1VecWidget.html#a72869862b8600d0f0ceb58ff66fd2e94',1,'ca::qt::VecWidget::vector()']]],
  ['vector_3c_20cell_20_3e_23',['vector&lt; Cell &gt;',['https://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20double_20_3e_24',['vector&lt; double &gt;',['https://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vecwidget_25',['VecWidget',['../classca_1_1qt_1_1VecWidget.html',1,'ca::qt']]],
  ['verices_5fcount_26',['verices_count',['../classca_1_1opt_1_1dijkstra.html#a0e8332999306f6182fc60eeb8b5c9a7c',1,'ca::opt::dijkstra::verices_count()'],['../classca_1_1opt_1_1floyd__warshall.html#a7e3bd72c1f6e03ff67f897f9abdb0a0e',1,'ca::opt::floyd_warshall::verices_count()']]],
  ['vfprintf_27',['vfprintf',['https://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_28',['vfscanf',['https://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_29',['vfwprintf',['https://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_30',['vfwscanf',['https://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vprintf_31',['vprintf',['https://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_32',['vscanf',['https://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_33',['vsnprintf',['https://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_34',['vsprintf',['https://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_35',['vsscanf',['https://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_36',['vswprintf',['https://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_37',['vswscanf',['https://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_38',['vwprintf',['https://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_39',['vwscanf',['https://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
